;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Init.Weapon.AmmoInMagazine",NewTagName="Init.Weapon.AmmoInMag")
+GameplayTagRedirects=(OldTagName="GameplayAbility.Movement.Teleport",NewTagName="GameplayAbility.Movement.ShadowStep")
+GameplayTagRedirects=(OldTagName="Cooldown.ShadowStap",NewTagName="Cooldown.ShadowStep")
+GameplayTagRedirects=(OldTagName="Cooldown.Decor",NewTagName="Cooldown.PlaceHolder")
+GameplayTagRedirects=(OldTagName="Data.Damage.SkillBase",NewTagName="Data.Damage.BaseSkillDamage")
+GameplayTagRedirects=(OldTagName="State.Burn",NewTagName="State.Burninig")
+GameplayTagRedirects=(OldTagName="State.Bleending",NewTagName="State.Bleeding")
+GameplayTagRedirects=(OldTagName="Cooldown.NovaFrozen",NewTagName="Cooldown.FrostNova")
+GameplayTagRedirects=(OldTagName="GameplayAbility.NovaFrozen",NewTagName="GameplayAbility.FrostNova")
+GameplayTagList=(Tag="Character.Class.Guardion",DevComment="")
+GameplayTagList=(Tag="Character.Class.Mage",DevComment="")
+GameplayTagList=(Tag="Character.Class.Shadow",DevComment="")
+GameplayTagList=(Tag="Combo.PhantomStrike.1Hit",DevComment="")
+GameplayTagList=(Tag="Combo.PhantomStrike.2Hit",DevComment="")
+GameplayTagList=(Tag="Combo.PhantomStrike.3Hit",DevComment="")
+GameplayTagList=(Tag="Cooldown.ChainLightning",DevComment="")
+GameplayTagList=(Tag="Cooldown.CroundSlam",DevComment="")
+GameplayTagList=(Tag="Cooldown.Dash",DevComment="")
+GameplayTagList=(Tag="Cooldown.DeathMark",DevComment="")
+GameplayTagList=(Tag="Cooldown.ElementalSurge",DevComment="")
+GameplayTagList=(Tag="Cooldown.Fireball",DevComment="")
+GameplayTagList=(Tag="Cooldown.Fortify",DevComment="")
+GameplayTagList=(Tag="Cooldown.FrostNova",DevComment="")
+GameplayTagList=(Tag="Cooldown.MeleeAttack",DevComment="")
+GameplayTagList=(Tag="Cooldown.PhantomStrike",DevComment="")
+GameplayTagList=(Tag="Cooldown.PlaceHolder",DevComment="")
+GameplayTagList=(Tag="Cooldown.ShadowStep",DevComment="")
+GameplayTagList=(Tag="Cooldown.ShieldBash",DevComment="")
+GameplayTagList=(Tag="Cooldown.SmokeBomb",DevComment="")
+GameplayTagList=(Tag="Cooldown.WarCry",DevComment="")
+GameplayTagList=(Tag="Data.Attributes.Defense",DevComment="")
+GameplayTagList=(Tag="Data.Attributes.Intelligence",DevComment="")
+GameplayTagList=(Tag="Data.Attributes.Strength",DevComment="")
+GameplayTagList=(Tag="Data.Cooldown.Duration",DevComment="")
+GameplayTagList=(Tag="Data.Cost.Amount",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Data.Damage.BaseSkillDamage",DevComment="")
+GameplayTagList=(Tag="Data.Damage.Fire",DevComment="")
+GameplayTagList=(Tag="Data.Damage.MultiplierEachLevel",DevComment="")
+GameplayTagList=(Tag="Data.Damage.MultiplierSkillDamage",DevComment="")
+GameplayTagList=(Tag="Data.DoT.DamagePerTick",DevComment="")
+GameplayTagList=(Tag="Data.Duration.Effect",DevComment="")
+GameplayTagList=(Tag="Event.Abilities.Change",DevComment="")
+GameplayTagList=(Tag="Event.Abilities.ComboClick",DevComment="")
+GameplayTagList=(Tag="Event.DamageIndicator",DevComment="")
+GameplayTagList=(Tag="Event.ShatterTriggered",DevComment="")
+GameplayTagList=(Tag="Event.Test",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.ChainLightning",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.DeathMark",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.ElementalSurge",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Fireball",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Fortify",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.FrostNova",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.GroundSlam",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Melee",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Movement.Dash",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Movement.ShadowStep",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.PhantomStrike",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.ShieldBash",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.SmokeBomb",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.WarCry",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ShadowStep.Appear",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ShadowStep.Vanish",DevComment="")
+GameplayTagList=(Tag="GameplayCue.UI.DamageNumber",DevComment="")
+GameplayTagList=(Tag="Init.Weapon.AmmoCurrent",DevComment="")
+GameplayTagList=(Tag="Init.Weapon.AmmoInMag",DevComment="")
+GameplayTagList=(Tag="Init.Weapon.NumberMag",DevComment="")
+GameplayTagList=(Tag="State.Bleeding",DevComment="")
+GameplayTagList=(Tag="State.Blind",DevComment="")
+GameplayTagList=(Tag="State.Burninig",DevComment="")
+GameplayTagList=(Tag="State.Dead",DevComment="")
+GameplayTagList=(Tag="State.EmPowered",DevComment="")
+GameplayTagList=(Tag="State.Fortifield",DevComment="")
+GameplayTagList=(Tag="State.Frozen",DevComment="")
+GameplayTagList=(Tag="State.Marked",DevComment="")
+GameplayTagList=(Tag="State.Shocked",DevComment="")
+GameplayTagList=(Tag="State.Slow",DevComment="")
+GameplayTagList=(Tag="State.Stun",DevComment="")
+GameplayTagList=(Tag="State.Surge",DevComment="")
+GameplayTagList=(Tag="State.Vulnerable",DevComment="")
+GameplayTagList=(Tag="Status.Regen.Stamina",DevComment="")
+GameplayTagList=(Tag="Status.Regen.Test",DevComment="")

